services:
  vault:
    image: hashicorp/vault
    container_name: "vault-github-issue-manager-service"
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "toor"
      VAULT_ADDR: "http://0.0.0.0:8200/"
      VAULT_API_ADDR: "http://0.0.0.0:8200/"
      VAULT_ADDRESS: "http://0.0.0.0:8200/"
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json